Lightbox gallery component
augustaspocius/fem-pdp-ecommerce-page pull request #6
Opened 2023-04-23 11:08 UTC by augustaspocius

2023-04-24 08:25 UTC, Kristute requested changes

2023-04-24 08:25 UTC, Kristute commented on src/components/ImageSlider.vue
> +  <Lightbox :current-slide="currentSlide" :images="images" :is-open="lightboxOpen" @close="lightboxOpen = false"
There are some warnings in the console
![Screenshot from 2023-04-24 10-48-06](https://user-images.githubusercontent.com/36459922/233932395-53dd1e6b-ae66-4bc3-aae7-30625a66a9ab.png)

2023-04-24 08:25 UTC, Kristute commented on src/components/Lightbox.vue
> +            <button class="absolute -top-8 right-0 w-5 h-5 flex justify-center items-center f" @click="$emit('close')">
The close button could be a bit bigger, and lightbox background a bit darker by the design

2023-04-24 08:25 UTC, Kristute commented on src/components/ImageSlider.vue
> +  data(): { lightboxOpen: boolean, currentSlide: number, images: string[] } {
`images` could be more descriptive, such as `productImages`.

2023-04-24 08:25 UTC, Kristute commented on src/components/ImageSlider.vue
> +    openLightbox() {
functions missing types

2023-04-24 08:25 UTC, Kristute commented on src/components/Lightbox.vue
> +        isOpen: Boolean,
Could be more descriptive, e.x. `isModalOpen`.

2023-04-24 08:25 UTC, Kristute commented on src/components/Lightbox.vue
> +            <button
Your code missing aria attributes. For example, buttons could have aria attributes to help users with disabilities understand their function.

2023-04-24 08:25 UTC, Kristute commented on src/components/Lightbox.vue
> +        nextSlide() {
missing types

2023-04-24 08:25 UTC, Kristute commented on src/components/Lightbox.vue
> +                        currentSlide === index ? '' : ''
You can use a computed property to calculate the `currentImage` based on the `currentSlide` index.

2023-04-24 08:25 UTC, Kristute commented on src/components/ImageSlider.vue
> +                 md:hidden" @click="previousSlide">
On the mobile part of the buttons hides outside the frame

2023-04-25 20:01 UTC, augustaspocius commented on src/components/Lightbox.vue
> +            <button class="absolute -top-8 right-0 w-5 h-5 flex justify-center items-center f" @click="$emit('close')">
Cannot make the button bigger, since svg won't let me do that for some reason

2023-04-28 09:55 UTC, Kristute commented on src/components/Lightbox.vue
> +            <button class="absolute -top-8 right-0 w-5 h-5 flex justify-center items-center f" @click="$emit('close')">
You could try using viewbox.
https://css-tricks.com/scale-svg/

2023-04-28 09:59 UTC, Kristute commented
Lightbox not working on mobile?

2023-04-28 10:06 UTC, Kristute commented on src/components/Lightbox.vue
> +            <button
close button could also have aria

2023-04-28 10:14 UTC, Kristute requested changes
Check light-box for mobile

2024-01-16 08:48 UTC, merged